/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.DaiBieuDAO;
import dto.Daibieu;
import gui.model.DaiBieuDataTableModel;
import java.awt.Color;
import java.io.File;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Admin
 */
public class frmQLDaiBieu extends javax.swing.JFrame {

    private ArrayList<Daibieu> listDaiBieu;
    private DaiBieuDataTableModel daibieudatatblemodel;
    private DaiBieuDAO daibieudao;
    private NewJFrame frmCheckin;

    private Date now = new Date();

    /**
     * Creates new form frmQLDaiBieu
     */
    public frmQLDaiBieu() {
        initComponents();
        daibieudatatblemodel = (DaiBieuDataTableModel) tblDaiBieu.getModel();
        tblDaiBieu.setRowSelectionAllowed(true);
        loadData();
        setup();
    }

    public void loadData() {
        listDaiBieu = daibieudao.loadAllDaiBieu();
        daibieudatatblemodel.setListDaiBieu(listDaiBieu);
    }
    
    public void setup(){
        String iconpath = System.getProperty("user.dir") + File.separator + "icon.png";
        File iconfile = new File(iconpath);
        ImageIcon icon = new ImageIcon(iconfile.getPath());
        this.setIconImage(icon.getImage());
        this.setTitle("Danh sách đại biểu");
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ckboxMale = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtboxID = new javax.swing.JTextField();
        txtboxMa = new javax.swing.JTextField();
        txtboxFirstName = new javax.swing.JTextField();
        txtboxLastName = new javax.swing.JTextField();
        txtboxClassify = new javax.swing.JTextField();
        datechooseBirthDay = new com.toedter.calendar.JDateChooser(now);
        txtboxHomeTown = new javax.swing.JTextField();
        txtboxEthnic = new javax.swing.JTextField();
        txtboxReligion = new javax.swing.JTextField();
        txtboxPosition = new javax.swing.JTextField();
        txtboxFaculty = new javax.swing.JTextField();
        txtboxAge = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDaiBieu = new javax.swing.JTable();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1200, 553));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Mã");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Họ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Tên");

        ckboxMale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ckboxMale.setSelected(true);
        ckboxMale.setText("Nam");
        ckboxMale.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ckboxMaleStateChanged(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Phân loại");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Ngày sinh");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Quê quán");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Dân tộc");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Tôn giáo");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Chức vụ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Đơn vị");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Tuổi");

        txtboxID.setPreferredSize(new java.awt.Dimension(50, 26));

        txtboxMa.setPreferredSize(new java.awt.Dimension(50, 26));

        txtboxFirstName.setPreferredSize(new java.awt.Dimension(150, 22));

        txtboxLastName.setPreferredSize(new java.awt.Dimension(100, 26));

        txtboxClassify.setPreferredSize(new java.awt.Dimension(50, 26));

        datechooseBirthDay.setDateFormatString("yyyy-MM-dd");
        datechooseBirthDay.setPreferredSize(new java.awt.Dimension(150, 26));
        datechooseBirthDay.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                datechooseBirthDayFocusLost(evt);
            }
        });
        datechooseBirthDay.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                datechooseBirthDayPropertyChange(evt);
            }
        });
        datechooseBirthDay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                datechooseBirthDayKeyReleased(evt);
            }
        });

        txtboxHomeTown.setPreferredSize(new java.awt.Dimension(100, 26));

        txtboxEthnic.setText("Kinh");
        txtboxEthnic.setPreferredSize(new java.awt.Dimension(100, 26));

        txtboxReligion.setText("Không");
        txtboxReligion.setPreferredSize(new java.awt.Dimension(100, 26));

        txtboxPosition.setPreferredSize(new java.awt.Dimension(200, 26));

        txtboxFaculty.setPreferredSize(new java.awt.Dimension(150, 26));

        txtboxAge.setPreferredSize(new java.awt.Dimension(50, 26));

        jButton2.setBackground(new java.awt.Color(0, 204, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("THÊM");
        jButton2.setPreferredSize(new java.awt.Dimension(130, 50));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("XÓA");
        jButton3.setEnabled(false);
        jButton3.setPreferredSize(new java.awt.Dimension(150, 50));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 204, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("CẬP NHẬT");
        jButton4.setEnabled(false);
        jButton4.setPreferredSize(new java.awt.Dimension(130, 50));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 204, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("CHECKIN");
        jButton5.setPreferredSize(new java.awt.Dimension(130, 50));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        tblDaiBieu.setModel(new DaiBieuDataTableModel());
        tblDaiBieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDaiBieuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDaiBieu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtboxID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtboxMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtboxFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtboxLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ckboxMale)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtboxClassify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(datechooseBirthDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtboxHomeTown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtboxEthnic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtboxReligion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtboxPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtboxFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtboxAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 24, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtboxID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(txtboxMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(txtboxFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(txtboxLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ckboxMale))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtboxClassify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addComponent(datechooseBirthDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(txtboxHomeTown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtboxEthnic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtboxReligion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtboxPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtboxFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtboxAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void datechooseBirthDayFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_datechooseBirthDayFocusLost

    }//GEN-LAST:event_datechooseBirthDayFocusLost

    private void ckboxMaleStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ckboxMaleStateChanged
        if (ckboxMale.isSelected()) {
            ckboxMale.setText("Nam");
        } else {
            ckboxMale.setText("Nữ");
        }
    }//GEN-LAST:event_ckboxMaleStateChanged

    private void datechooseBirthDayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_datechooseBirthDayKeyReleased

    }//GEN-LAST:event_datechooseBirthDayKeyReleased

    private void datechooseBirthDayPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_datechooseBirthDayPropertyChange
//        Date birthday = datechooseBirthDay.getDate();
//        long age = now.getTime() - birthday.getTime();
//        age /= 31536000000.0;
//        txtboxAge.setText(age + "");
    }//GEN-LAST:event_datechooseBirthDayPropertyChange

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        frmCheckin = new NewJFrame();
        frmCheckin.setSize(800, 450);
        frmCheckin.setVisible(true);
        frmCheckin.setEnabled(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tblDaiBieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDaiBieuMouseClicked
        int index = tblDaiBieu.getSelectedRow();
        Daibieu daibieu = new Daibieu();
        if (index >= 0) {
            daibieu = daibieudatatblemodel.getDaiBieu(index);
            txtboxID.setText(daibieu.getDbId() + "");
            txtboxMa.setText(daibieu.getDbSbd());
            txtboxFirstName.setText(daibieu.getDbFirstname());
            txtboxLastName.setText(daibieu.getDbLastname());
            if (daibieu.isDbMale()) {
                ckboxMale.setSelected(true);
            } else {
                ckboxMale.setSelected(false);
            }
            txtboxClassify.setText(daibieu.getDbClassify());
            datechooseBirthDay.setDate(daibieu.getDbBirthday());
            txtboxEthnic.setText(daibieu.getDbEthnic());
            txtboxReligion.setText(daibieu.getDbReligion());
            txtboxPosition.setText(daibieu.getDbPosition());
            txtboxFaculty.setText(daibieu.getDbFaculty());
            txtboxAge.setText(daibieu.getDbAge() + "");
            txtboxHomeTown.setText(daibieu.getDbHome());
        }
        jButton3.setEnabled(true);
        jButton4.setEnabled(true);
    }//GEN-LAST:event_tblDaiBieuMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int id = Integer.parseInt(txtboxID.getText());
        String sbd = txtboxMa.getText();
        String firstname = txtboxFirstName.getText();
        String lastname = txtboxLastName.getText();
        boolean male = true;
        if (!ckboxMale.isSelected()) {
            male = false;
        }
        String classify = txtboxClassify.getText();
        Date birthday = datechooseBirthDay.getDate();
        String ethnic = txtboxEthnic.getText();
        String religion = txtboxReligion.getText();
        String position = txtboxPosition.getText();
        String faculty = txtboxFaculty.getText();
        int age = Integer.parseInt(txtboxAge.getText());
        String home = txtboxHomeTown.getText();
        Daibieu db = new Daibieu(id, sbd, firstname, lastname, male, classify, birthday, home, ethnic, religion, position, faculty, age);
        DaiBieuDAO.addDaiBieu(db);
        txtboxID.setText("");
        txtboxMa.setText("");
        txtboxFirstName.setText("");
        txtboxLastName.setText("");
        ckboxMale.setSelected(true);
        txtboxClassify.setText("");
        datechooseBirthDay.setDate(now);
        txtboxEthnic.setText("Kinh");
        txtboxReligion.setText("Không");
        txtboxPosition.setText("");
        txtboxFaculty.setText("");
        txtboxAge.setText("");
        txtboxHomeTown.setText("");
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        daibieudatatblemodel.fireTableDataChanged();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int index = tblDaiBieu.getSelectedRow();
        Daibieu daibieu = new Daibieu();
        if (index >= 0) {
            daibieu = daibieudatatblemodel.getDaiBieu(index);
            DaiBieuDAO.delDaiBieu(daibieu);
        }
        txtboxID.setText("");
        txtboxMa.setText("");
        txtboxFirstName.setText("");
        txtboxLastName.setText("");
        ckboxMale.setSelected(true);
        txtboxClassify.setText("");
        datechooseBirthDay.setDate(now);
        txtboxEthnic.setText("Kinh");
        txtboxReligion.setText("Không");
        txtboxPosition.setText("");
        txtboxFaculty.setText("");
        txtboxAge.setText("");
        txtboxHomeTown.setText("");
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        daibieudatatblemodel.fireTableDataChanged();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int index = tblDaiBieu.getSelectedRow();
        Daibieu daibieu = new Daibieu();
        if (index >= 0) {
            daibieu = daibieudatatblemodel.getDaiBieu(index);
            
            daibieu.setDbSbd(txtboxMa.getText());
            daibieu.setDbFirstname(txtboxFirstName.getText());
            daibieu.setDbLastname(txtboxLastName.getText());
            daibieu.setDbMale(ckboxMale.isSelected());
            daibieu.setDbClassify(txtboxClassify.getText());
            daibieu.setDbBirthday(datechooseBirthDay.getDate());
            daibieu.setDbEthnic(txtboxEthnic.getText());
            daibieu.setDbReligion(txtboxReligion.getText());
            daibieu.setDbPosition(txtboxPosition.getText());
            daibieu.setDbFaculty(txtboxFaculty.getText());
            daibieu.setDbAge(Integer.parseInt(txtboxAge.getText()));
            daibieu.setDbHome(txtboxHomeTown.getText());
            DaiBieuDAO.delDaiBieu(daibieu);
            DaiBieuDAO.updateDaiBieu(daibieu);
        }
        txtboxID.setText("");
        txtboxMa.setText("");
        txtboxFirstName.setText("");
        txtboxLastName.setText("");
        ckboxMale.setSelected(true);
        txtboxClassify.setText("");
        datechooseBirthDay.setDate(now);
        txtboxEthnic.setText("Kinh");
        txtboxReligion.setText("Không");
        txtboxPosition.setText("");
        txtboxFaculty.setText("");
        txtboxAge.setText("");
        txtboxHomeTown.setText("");
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        daibieudatatblemodel.fireTableDataChanged();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmQLDaiBieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmQLDaiBieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmQLDaiBieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmQLDaiBieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmQLDaiBieu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ckboxMale;
    private com.toedter.calendar.JDateChooser datechooseBirthDay;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDaiBieu;
    private javax.swing.JTextField txtboxAge;
    private javax.swing.JTextField txtboxClassify;
    private javax.swing.JTextField txtboxEthnic;
    private javax.swing.JTextField txtboxFaculty;
    private javax.swing.JTextField txtboxFirstName;
    private javax.swing.JTextField txtboxHomeTown;
    private javax.swing.JTextField txtboxID;
    private javax.swing.JTextField txtboxLastName;
    private javax.swing.JTextField txtboxMa;
    private javax.swing.JTextField txtboxPosition;
    private javax.swing.JTextField txtboxReligion;
    // End of variables declaration//GEN-END:variables
}
