/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dto.Daibieu;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.MediaTracker;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Admin
 */
public class frmShowInfo extends javax.swing.JFrame {
    
    private Daibieu daibieu;

    public Daibieu getDaibieu() {
        return daibieu;
    }

    public void setDaibieu(Daibieu daibieu) {
        this.daibieu = daibieu;
    }

    /**
     * Creates new form frmShowInfo
     */
    public frmShowInfo() {
        initComponents();
        daibieu = null;
        setup();
    }
    
    public frmShowInfo(Daibieu daibieu) throws HeadlessException {
        this.daibieu = daibieu;
        setup();
    }
    
    public void setup() {
        String iconpath = System.getProperty("user.dir") + File.separator + "icon.png";
        File iconfile = new File(iconpath);
        ImageIcon icon = new ImageIcon(iconfile.getPath());
        this.setIconImage(icon.getImage());
        this.setTitle("CHÀO MỪNG ĐẠI HỘI ĐẠI BIỂU HỘI SINH VIÊN TRƯỜNG ĐẠI HỌC CÔNG NGHỆ SÀI GÒN NHIỆM KỲ VI");
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setBackground(Color.WHITE);
        this.getContentPane().setBackground(Color.WHITE);
//        String path = System.getProperty("user.dir") + File.separator + "logo.png";
//        File filePath = new File(path);
//        panelLogo = new ContentPanel();
        
        if (daibieu != null) {
            txtboxSBD.setText(daibieu.getDbSbd());
            txtboxFirstName.setText(daibieu.getDbFirstname());
            txtboxLastName.setText(daibieu.getDbLastname());
            if (daibieu.isDbMale()) {
                txtboxGender.setText("Nam");
            } else {
                txtboxGender.setText("Nữ");
            }
            txtboxClassify.setText(daibieu.getDbClassify());
            txtboxBirthday.setText(daibieu.getDbBirthday() + "");
            txtboxEthnic.setText(daibieu.getDbEthnic());
            txtboxReligion.setText(daibieu.getDbReligion());
            txtboxPossition.setText(daibieu.getDbPosition());
            txtboxFaculty.setText(daibieu.getDbFaculty());
            txtboxAge.setText(daibieu.getDbAge() + "");
            txtboxHome.setText(daibieu.getDbHome());
        } else {
            reset();
        }    
    }
    
    public void reset() {
        txtboxSBD.setText("");
        txtboxFirstName.setText("");
        txtboxLastName.setText("");
        txtboxGender.setText("");
        txtboxClassify.setText("");
        txtboxBirthday.setText("");
        txtboxEthnic.setText("");
        txtboxReligion.setText("");
        txtboxPossition.setText("");
        txtboxFaculty.setText("");
        txtboxAge.setText("");
        txtboxHome.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtboxPossition = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtboxSBD = new javax.swing.JTextField();
        txtboxFaculty = new javax.swing.JTextField();
        txtboxAge = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtboxFirstName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtboxLastName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtboxGender = new javax.swing.JTextField();
        txtboxClassify = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtboxBirthday = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtboxHome = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtboxEthnic = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtboxReligion = new javax.swing.JTextField();
        panelLogo = new ContentPanel();

        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        setSize(new java.awt.Dimension(1366, 768));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(getPreferredSize());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 255));
        jLabel1.setText("SBD");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 204, 255));
        jLabel12.setText("Tuổi");

        txtboxPossition.setEditable(false);
        txtboxPossition.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtboxPossition.setBorder(null);
        txtboxPossition.setFocusable(false);
        txtboxPossition.setPreferredSize(new java.awt.Dimension(600, 44));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 255));
        jLabel2.setText("Họ và tên");

        txtboxSBD.setEditable(false);
        txtboxSBD.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtboxSBD.setBorder(null);
        txtboxSBD.setFocusable(false);
        txtboxSBD.setPreferredSize(new java.awt.Dimension(400, 44));
        txtboxSBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtboxSBDActionPerformed(evt);
            }
        });

        txtboxFaculty.setEditable(false);
        txtboxFaculty.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtboxFaculty.setBorder(null);
        txtboxFaculty.setFocusable(false);
        txtboxFaculty.setPreferredSize(new java.awt.Dimension(400, 44));

        txtboxAge.setEditable(false);
        txtboxAge.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtboxAge.setBorder(null);
        txtboxAge.setFocusable(false);
        txtboxAge.setPreferredSize(new java.awt.Dimension(400, 44));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 255));
        jLabel4.setText("Giới tính");

        txtboxFirstName.setEditable(false);
        txtboxFirstName.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtboxFirstName.setBorder(null);
        txtboxFirstName.setFocusable(false);
        txtboxFirstName.setPreferredSize(new java.awt.Dimension(400, 44));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 255));
        jLabel5.setText("Phân loại đại biểu");

        txtboxLastName.setEditable(false);
        txtboxLastName.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtboxLastName.setBorder(null);
        txtboxLastName.setFocusable(false);
        txtboxLastName.setPreferredSize(new java.awt.Dimension(200, 44));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 255));
        jLabel6.setText("Ngày sinh");

        txtboxGender.setEditable(false);
        txtboxGender.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtboxGender.setBorder(null);
        txtboxGender.setFocusable(false);
        txtboxGender.setPreferredSize(new java.awt.Dimension(400, 44));

        txtboxClassify.setEditable(false);
        txtboxClassify.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtboxClassify.setBorder(null);
        txtboxClassify.setFocusable(false);
        txtboxClassify.setPreferredSize(new java.awt.Dimension(400, 44));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 255));
        jLabel3.setText("Quên quán");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 255));
        jLabel8.setText("Dân tộc");

        txtboxBirthday.setEditable(false);
        txtboxBirthday.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtboxBirthday.setBorder(null);
        txtboxBirthday.setFocusable(false);
        txtboxBirthday.setPreferredSize(new java.awt.Dimension(400, 44));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 255));
        jLabel9.setText("Tôn giáo");

        txtboxHome.setEditable(false);
        txtboxHome.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtboxHome.setBorder(null);
        txtboxHome.setFocusable(false);
        txtboxHome.setPreferredSize(new java.awt.Dimension(400, 44));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 204, 255));
        jLabel10.setText("Chức vụ");

        txtboxEthnic.setEditable(false);
        txtboxEthnic.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtboxEthnic.setBorder(null);
        txtboxEthnic.setFocusable(false);
        txtboxEthnic.setPreferredSize(new java.awt.Dimension(400, 44));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 204, 255));
        jLabel11.setText("Khoa");

        txtboxReligion.setEditable(false);
        txtboxReligion.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtboxReligion.setBorder(null);
        txtboxReligion.setFocusable(false);
        txtboxReligion.setPreferredSize(new java.awt.Dimension(400, 44));

        panelLogo.setBackground(new java.awt.Color(255, 255, 255));
        panelLogo.setPreferredSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout panelLogoLayout = new javax.swing.GroupLayout(panelLogo);
        panelLogo.setLayout(panelLogoLayout);
        panelLogoLayout.setHorizontalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        panelLogoLayout.setVerticalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtboxAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtboxFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtboxPossition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtboxReligion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtboxEthnic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtboxHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtboxBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtboxSBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtboxFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(txtboxLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtboxGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtboxClassify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtboxSBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtboxFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtboxLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtboxGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtboxClassify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtboxBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtboxHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtboxEthnic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtboxReligion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtboxPossition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addComponent(panelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtboxFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtboxAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtboxSBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtboxSBDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtboxSBDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmShowInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmShowInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmShowInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmShowInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmShowInfo().setVisible(true);
            }
        });
    }
    
    
    
    class ContentPanel extends JPanel {
        
        Image bgimage = null;
        
        ContentPanel() {
            MediaTracker mt = new MediaTracker(this);
            String path = System.getProperty("user.dir") + File.separator + "logo.png";
            bgimage = Toolkit.getDefaultToolkit().getImage(path);
            mt.addImage(bgimage, 0, 10, 10);
            try {
                mt.waitForAll();
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
        
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            int imwidth = bgimage.getWidth(null);
            int imheight = bgimage.getHeight(null);
            g.drawImage(bgimage, 1, 1, Color.WHITE, null);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelLogo;
    private javax.swing.JTextField txtboxAge;
    private javax.swing.JTextField txtboxBirthday;
    private javax.swing.JTextField txtboxClassify;
    private javax.swing.JTextField txtboxEthnic;
    private javax.swing.JTextField txtboxFaculty;
    private javax.swing.JTextField txtboxFirstName;
    private javax.swing.JTextField txtboxGender;
    private javax.swing.JTextField txtboxHome;
    private javax.swing.JTextField txtboxLastName;
    private javax.swing.JTextField txtboxPossition;
    private javax.swing.JTextField txtboxReligion;
    private javax.swing.JTextField txtboxSBD;
    // End of variables declaration//GEN-END:variables
}
