package dto;
// Generated Jun 11, 2018 8:49:01 PM by Hibernate Tools 4.3.1

/**
 * Checkin generated by hbm2java
 */
public class Checkin implements java.io.Serializable {

    private int ckId;
    private Daibieu daibieu;
    private boolean ckCheck1;
    private boolean ckCheck2;
    private Boolean ckCheck3;
    private boolean ckCheck4;
    private boolean ckCheck5;

    public Checkin() {
    }

    public Checkin(Daibieu daibieu, boolean ckCheck1, boolean ckCheck2, boolean ckCheck4, boolean ckCheck5) {
        this.daibieu = daibieu;
        this.ckCheck1 = ckCheck1;
        this.ckCheck2 = ckCheck2;
        this.ckCheck4 = ckCheck4;
        this.ckCheck5 = ckCheck5;
    }

    public Checkin(Daibieu daibieu, boolean ckCheck1, boolean ckCheck2, Boolean ckCheck3, boolean ckCheck4, boolean ckCheck5) {
        this.daibieu = daibieu;
        this.ckCheck1 = ckCheck1;
        this.ckCheck2 = ckCheck2;
        this.ckCheck3 = ckCheck3;
        this.ckCheck4 = ckCheck4;
        this.ckCheck5 = ckCheck5;
    }

    public int getCkId() {
        return this.ckId;
    }

    public void setCkId(int ckId) {
        this.ckId = ckId;
    }

    public Daibieu getDaibieu() {
        return this.daibieu;
    }

    public void setDaibieu(Daibieu daibieu) {
        this.daibieu = daibieu;
    }

    public boolean isCkCheck1() {
        return this.ckCheck1;
    }

    public void setCkCheck1(boolean ckCheck1) {
        this.ckCheck1 = ckCheck1;
    }

    public boolean isCkCheck2() {
        return this.ckCheck2;
    }

    public void setCkCheck2(boolean ckCheck2) {
        this.ckCheck2 = ckCheck2;
    }

    public Boolean getCkCheck3() {
        return this.ckCheck3;
    }

    public void setCkCheck3(Boolean ckCheck3) {
        this.ckCheck3 = ckCheck3;
    }

    public boolean isCkCheck4() {
        return this.ckCheck4;
    }

    public void setCkCheck4(boolean ckCheck4) {
        this.ckCheck4 = ckCheck4;
    }

    public boolean isCkCheck5() {
        return this.ckCheck5;
    }

    public void setCkCheck5(boolean ckCheck5) {
        this.ckCheck5 = ckCheck5;
    }

    @Override
    public String toString() {
        return "Checkin{" + "ckId=" + ckId + ", daibieu=" + daibieu + ", ckCheck1=" + ckCheck1 + ", ckCheck2=" + ckCheck2 + ", ckCheck3=" + ckCheck3 + ", ckCheck4=" + ckCheck4 + ", ckCheck5=" + ckCheck5 + '}';
    }

}
