package dto;
// Generated Jun 11, 2018 8:49:01 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Daibieu generated by hbm2java
 */
public class Daibieu implements java.io.Serializable {

    private int dbId;
    private String dbSbd;
    private String dbFirstname;
    private String dbLastname;
    private boolean dbMale;
    private String dbClassify;
    private Date dbBirthday;
    private String dbHome;
    private String dbEthnic;
    private String dbReligion;
    private String dbPosition;
    private String dbFaculty;
    private int dbAge;
    private Checkin checkin;

    public Daibieu() {
    }

    public Daibieu(int dbId, String dbSbd, String dbFirstname, String dbLastname, boolean dbMale, String dbClassify, Date dbBirthday, String dbHome, String dbEthnic, String dbReligion, String dbPosition, String dbFaculty, int dbAge) {
        this.dbId = dbId;
        this.dbSbd = dbSbd;
        this.dbFirstname = dbFirstname;
        this.dbLastname = dbLastname;
        this.dbMale = dbMale;
        this.dbClassify = dbClassify;
        this.dbBirthday = dbBirthday;
        this.dbHome = dbHome;
        this.dbEthnic = dbEthnic;
        this.dbReligion = dbReligion;
        this.dbPosition = dbPosition;
        this.dbFaculty = dbFaculty;
        this.dbAge = dbAge;
    }

    public Daibieu(int dbId, String dbSbd, String dbFirstname, String dbLastname, boolean dbMale, String dbClassify, Date dbBirthday, String dbHome, String dbEthnic, String dbReligion, String dbPosition, String dbFaculty, int dbAge, Checkin checkin) {
        this.dbId = dbId;
        this.dbSbd = dbSbd;
        this.dbFirstname = dbFirstname;
        this.dbLastname = dbLastname;
        this.dbMale = dbMale;
        this.dbClassify = dbClassify;
        this.dbBirthday = dbBirthday;
        this.dbHome = dbHome;
        this.dbEthnic = dbEthnic;
        this.dbReligion = dbReligion;
        this.dbPosition = dbPosition;
        this.dbFaculty = dbFaculty;
        this.dbAge = dbAge;
        this.checkin = checkin;
    }

    public int getDbId() {
        return this.dbId;
    }

    public void setDbId(int dbId) {
        this.dbId = dbId;
    }

    public String getDbSbd() {
        return this.dbSbd;
    }

    public void setDbSbd(String dbSbd) {
        this.dbSbd = dbSbd;
    }

    public String getDbFirstname() {
        return this.dbFirstname;
    }

    public void setDbFirstname(String dbFirstname) {
        this.dbFirstname = dbFirstname;
    }

    public String getDbLastname() {
        return this.dbLastname;
    }

    public void setDbLastname(String dbLastname) {
        this.dbLastname = dbLastname;
    }

    public boolean isDbMale() {
        return this.dbMale;
    }

    public void setDbMale(boolean dbMale) {
        this.dbMale = dbMale;
    }

    public String getDbClassify() {
        return this.dbClassify;
    }

    public void setDbClassify(String dbClassify) {
        this.dbClassify = dbClassify;
    }

    public Date getDbBirthday() {
        return this.dbBirthday;
    }

    public void setDbBirthday(Date dbBirthday) {
        this.dbBirthday = dbBirthday;
    }

    public String getDbHome() {
        return this.dbHome;
    }

    public void setDbHome(String dbHome) {
        this.dbHome = dbHome;
    }

    public String getDbEthnic() {
        return this.dbEthnic;
    }

    public void setDbEthnic(String dbEthnic) {
        this.dbEthnic = dbEthnic;
    }

    public String getDbReligion() {
        return this.dbReligion;
    }

    public void setDbReligion(String dbReligion) {
        this.dbReligion = dbReligion;
    }

    public String getDbPosition() {
        return this.dbPosition;
    }

    public void setDbPosition(String dbPosition) {
        this.dbPosition = dbPosition;
    }

    public String getDbFaculty() {
        return this.dbFaculty;
    }

    public void setDbFaculty(String dbFaculty) {
        this.dbFaculty = dbFaculty;
    }

    public int getDbAge() {
        return this.dbAge;
    }

    public void setDbAge(int dbAge) {
        this.dbAge = dbAge;
    }

    public Checkin getCheckin() {
        return this.checkin;
    }

    public void setCheckin(Checkin checkin) {
        this.checkin = checkin;
    }

    @Override
    public String toString() {
        return "Daibieu{" + "dbId=" + dbId + ", dbSbd=" + dbSbd + ", dbFirstname=" + dbFirstname + ", dbLastname=" + dbLastname + ", dbMale=" + dbMale + ", dbClassify=" + dbClassify + ", dbBirthday=" + dbBirthday + ", dbHome=" + dbHome + ", dbEthnic=" + dbEthnic + ", dbReligion=" + dbReligion + ", dbPosition=" + dbPosition + ", dbFaculty=" + dbFaculty + ", dbAge=" + dbAge + '}';
    }

}
